//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpsIntel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VMAutomationRule
    {
        public int Id { get; set; }
        public int VMID { get; set; }
        public string UtilizationType { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string Action { get; set; }
        public string Value { get; set; }
        public string ResizeTo { get; set; }
        public Nullable<System.DateTime> LastExecutedOn { get; set; }
    }
}
